name: vdsadmin
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.14.0-116.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter:
  dotted_border: 
  file_picker:
  image_picker: 
  # timelines: 
  timelines_plus: ^1.0.8
  flutter_barcode_scanner: 
  cached_network_image:
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore:
  permission_handler:
  firebase_storage:
  fluttertoast:
  visibility_detector: 
  flutter_barcode_listener: 
  auto_size_text:
  image_picker_web:
  
  google_fonts: 
  
  pdf: 
  open_file: 
  intl: 
  whatsapp_share: 
  screenshot:
  pdf_viewer_plugin: 
  shared_preferences: 
  # carousel_pro: ^1.0.0
  # flutter_neumorphic: 
  flutter_share: 
  firebase_dynamic_links: 
  firebase_messaging:
  onesignal_flutter:
  http:
  transparent_image: 
  syncfusion_flutter_pdf: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: 
  change_app_package_name: 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - images/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Nunito
       fonts:
         - asset: fonts/Nunito-Regular.ttf
     - family: OpenSans
       fonts:
         - asset: assets/open-sans.ttf
     - family: OpenSans
       fonts:
         - asset: fonts/Poppins-Regular.ttf
         - asset: fonts/Poppins-Bold.ttf
     - family: Hind
       fonts:
         - asset: fonts/Hind-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
