name: ecom_admin_panel
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.1
  firebase_core: ^2.24.1
  firebase_database: ^10.3.5
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.5.4
  dotted_border: ^3.1.0
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1
  # multi_select_flutter: ^4.3.2
  # timelines: ^0.1.0
  timelines_plus: ^1.0.8
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0