// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTyLenFGsYRnj1xc2PIscTq7Fk_H4OFec',
    appId: '1:135817720188:web:24e99ce5150a2ddca3b4f9',
    messagingSenderId: '135817720188',
    projectId: 'vaibhav-s-ecommerce-app',
    authDomain: 'vaibhav-s-ecommerce-app.firebaseapp.com',
    databaseURL: 'https://vaibhav-s-ecommerce-app.firebaseio.com',
    storageBucket: 'vaibhav-s-ecommerce-app.appspot.com',
    measurementId: 'G-N7GNH4NRYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_YMZV4Zny306NUTmNNijeE7gCGs0eK4A',
    appId: '1:135817720188:android:6ec49e2e41ba42b6a3b4f9',
    messagingSenderId: '135817720188',
    projectId: 'vaibhav-s-ecommerce-app',
    databaseURL: 'https://vaibhav-s-ecommerce-app.firebaseio.com',
    storageBucket: 'vaibhav-s-ecommerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmyXoI36rVHsDRl4RE9j4JwWhedEX96pc',
    appId: '1:135817720188:ios:22eaf41249eeabfca3b4f9',
    messagingSenderId: '135817720188',
    projectId: 'vaibhav-s-ecommerce-app',
    databaseURL: 'https://vaibhav-s-ecommerce-app.firebaseio.com',
    storageBucket: 'vaibhav-s-ecommerce-app.appspot.com',
    iosClientId: '135817720188-v5fr78s7v0qpstimt83mmt9ro8qv2tbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.emart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmyXoI36rVHsDRl4RE9j4JwWhedEX96pc',
    appId: '1:135817720188:ios:e9c85e4800f6d341a3b4f9',
    messagingSenderId: '135817720188',
    projectId: 'vaibhav-s-ecommerce-app',
    databaseURL: 'https://vaibhav-s-ecommerce-app.firebaseio.com',
    storageBucket: 'vaibhav-s-ecommerce-app.appspot.com',
    iosClientId: '135817720188-pucosiho09np8cvvc602ki5pcth7258o.apps.googleusercontent.com',
    iosBundleId: 'com.example.emart.RunnerTests',
  );
}
